### PR TITLE
Alert/button

### PR DESCRIPTION
**Pull request by chanchal16**
- Created alert and button components.
- updated styles

### CODE REVIEW

**Review by NtshVrm — APPROVED** [review]

**Comment by ivinayakg** [comment]
`.btn-container{
    max-width: 600px;
    border: 1px solid grey;
    padding: 2rem;
    display: flex;
    gap: 20px;
    margin: 1rem;
}
.btn{
    padding: 8px 12px;
    color: white;
    border:none;
    border-radius: 5px;
    cursor: pointer;
}`

don't use a wrapper container for button as it will bring unnecessary complications on implementation in the future.

**Comment by ajit-sharmaGH** [comment]
Hey i went through the code, it looks fine to merge 😎!

**Comment by ivinayakg** [comment]
#2 
in the button you have used button container, it will bring unnecessary complications in the future
don't use :hover for different elements like for "i:hover" or "fab:hover" again it will slow down the development process rather think about a very simple change like translate or opacity for the hover and give it to the button itself and not to its child

P.S - these are very small and minor changes you would need to do but don't get discourage anyone would make these mistakes in the beginning😊

#1 
alert looks good

**Comment by chanchal16** [comment]
> #2 in the button you have used button container, it will bring unnecessary complications in the future don't use :hover for different elements like for "i:hover" or "fab:hover" again it will slow down the development process rather think about a very simple change like translate or opacity for the hover and give it to the button itself and not to its child
> 
> P.S - these are very small and minor changes you would need to do but don't get discourage anyone would make these mistakes in the beginning😊
> 
> #1 alert looks good

Yes, I am going to remove the button container later. I think you misunderstood it, I have given the hover effect to the button itself and not to its child.
Thanks for the feedback!!

**Pull request merged**
