### PR TITLE
List/navbars

### PR DESCRIPTION
**Pull request by chanchal16**
- Created list and navbars
- simple list
- stacked list
- simple navbar
- navbar with links on left side
- navbar with icon links

### CODE REVIEW

**Comment by sandeepkumardev-zz** [comment]
looks good 👍

**Comment by biswanath-tewari** [comment]
looks all good to merge

**Comment by SanjayJatti** [comment]
You can add live demo of component by adding gif or live link. So that It will help reviewers. 
Besides all looking clean.

**Comment by chanchal16** [comment]
> You can add live demo of component by adding gif or live link. So that It will help reviewers. Besides all looking clean.

okay, will do that next time.

**Pull request merged**
