### PR TITLE
Cards

### PR DESCRIPTION
**Pull request by chanchal16**
- Created cards component.
- card with badge and shadow.
- card with dismiss.
- card with text overlay.
- horizontal card
- text-only card.

### CODE REVIEW

**Comment by ivinayakg** [comment]
apart from that, your code looks good 👍

**Review by NtshVrm — APPROVED** [review]

**Review by maitrakhatri — APPROVED** [review]
everything looks good !! just one suggestion, some dimensions are in px and some in rem. So it might cause issues and not look consistent across different screen sizes, so make sure all of your dimensions are in one unit only.

**Comment by chanchal16** [comment]
> apart from that, your code looks good 👍

Thanks for the feedback!!

**Comment by chanchal16** [comment]
> everything looks good !! just one suggestion, some dimensions are in px and some in rem. So it might cause issues and not look consistent across different screen sizes, so make sure all of your dimensions are in one unit only.

I will keep that in mind and make the changes.
Thanks for the feedback!!

**Comment by kiranpratyush** [comment]
The Code looks good.

**Review by kiranpratyush — APPROVED** [review]

**Comment by chanchal16** [comment]
> The Code looks good.

Thanks for the feedback!!

**Pull request merged**
